FROM php:8.5-fpm AS base

ENV TZ=Europe/Zurich
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim curl zip unzip git pkg-config \
    libcurl4-openssl-dev \
    libzip-dev \
    zlib1g-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libldap2-dev \
    libicu-dev \
    libmagickwand-dev \
    imagemagick \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
    pdo pdo_mysql bcmath mbstring gd intl

RUN pecl install imagick \
&& docker-php-ext-enable imagick


FROM base AS build

WORKDIR /app
COPY . /app

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
&& apt-get install -y nodejs

RUN composer install --no-interaction --prefer-dist
RUN npm install
RUN npm run build || true


FROM base AS prod

WORKDIR /app
COPY --from=build /app /app

USER root
