name: Tests

on:
  push:
  #branches: [ "main" ]
  pull_request:
  #branches: [ main ]
  workflow_call: 

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]#ubuntu-latest# #windows-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      MODULE_PATH: "github.com/mattia37773"
      APP_NAME: "mt"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      #  * --- DOCKER SETUP JE NACH OS ---
      #colima start --vm-type=qemu --cpu 2 --memory 4
      - name: Setup Docker (macOS)
        if: runner.os == 'macOS'
        run: |

          brew install colima docker docker-compose
          # brew install docker-buildx

          mkdir -p ~/.docker/cli-plugins
          ln -sfn $(brew --prefix)/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          #ln -sfn $(brew --prefix)/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx

          colima start \
            --arch aarch64 \
            --vm-type=qemu \
            --nested-virtualization

      - name: Verify Docker Setup
        run: |
          docker info
          docker --version
          docker compose version

      # *--- TESTSUITE ---
      - name: Running Testsuite
        run: |
          echo "Testing with unittests..."
          echo

          # Dateiendung für Windows berücksichtigen (.exe)
          EXE=""
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXE=".exe"
          fi

          mkdir -p tests/bin

          echo "Removing old binaries"
          rm -f tests/bin/homebrew-install$EXE
          rm -f tests/bin/go-install$EXE
          rm -f tests/bin/source-install$EXE

          echo "Building binaries for testing update"
          echo

          # source install
          go build \
            -ldflags="\
              -X '${MODULE_PATH}/${APP_NAME}/config.OverrideCurrentVersion=v1.0.0' \
              -X '${MODULE_PATH}/${APP_NAME}/config.OverrideBuildMethod=source'" \
            -o tests/bin/source-install$EXE

          # go install
          go build \
            -ldflags="\
              -X '${MODULE_PATH}/${APP_NAME}/config.OverrideCurrentVersion=v1.0.0'" \
            -o tests/bin/go-install$EXE

          # homebrew install
          go build \
            -ldflags="\
              -X '${MODULE_PATH}/${APP_NAME}/config.OverrideCurrentVersion=v1.0.0' \
              -X '${MODULE_PATH}/${APP_NAME}/config.OverrideBuildMethod=homebrew'" \
            -o tests/bin/homebrew-install$EXE

          go clean -cache
          go test -v -p 1 ./tests/cmd/... -ldflags="\
            -X '${MODULE_PATH}/${APP_NAME}/config.OverrideCurrentVersion=v1.0.0'" \
            ./... 

          echo "Removing the binaries"
          rm -f tests/bin/homebrew-install$EXE
          rm -f tests/bin/go-install$EXE
          rm -f tests/bin/source-install$EXE
